on:
  workflow_dispatch:  

name: Pipeline Staging

jobs:
  release-please:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code  
        uses: actions/checkout@v2
      
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '14'  
      
      - name: Install dependencies  
        run: npm install
      
      - name: Run release-please  
        uses: nodejs/setup-node@v2  
        with:
          node-version: '12'  
          release-type: node  
          package-name: release-please-action  
